apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitwarden
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: SecretStore
  data:
  - secretKey: dex.grafana
    remoteRef:
      key: "6e707aec-b14c-4c4e-a375-b22600298711"
